CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE UNLOGGED TABLE IF NOT EXISTS people (
    id uuid PRIMARY KEY DEFAULT uuidv7(),
    nickname VARCHAR(32) UNIQUE NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    birth_date DATE NOT NULL,
    stack VARCHAR(32)[] DEFAULT '{}' NOT NULL
);
